# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blamo', '0002_blamohost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blamohost',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
